### ISSUE TITLE
Pasting images from clipboard cause to 'Failed to process the file'

### ISSUE THREAD

**Issue by QNoir** [alberti42/obsidian-import-attachments-plus#3]
Hello, 

I'm not sure is it a bug or a planned behaviour, but when I'm trying to paste images from clipboard (for example, after copying from the web page), I get the error 'Failed to process the file'. 
all other settings work correctly: the folder is creating, but the image is not saved there, and nothing is pasting to the note. 

if this is not a bug I would like to request such feature as processing attaches from clipboard. 
I tried different plugins: Attachment Manager, Attachment Management, Custom Attachment Location, but all of them doesn't work as required or has no all required features. 

your plugin is the first one that does exactly what I need with folders and attachments, and thank you very much for it! 
if only he had also worked with pasting of the attaches from the clipboard - it would be exactly what I'm searching for!

**Comment by alberti42** [comment]
Thanks for the feedback. I experienced the same problem myself. It will be fixed very likely in the next 10 days. For sure, I plan to improve many things and remove these remaining problems from the plugin. I also need to improve compatibility with Windows. Sorry, I am doing this in the spare weekends, so I hope you understand if I cannot immediately fix the problem.

**Comment by alberti42** [comment]
The current version fixes this problem and many other issues. It is not released yet, but if you want to try it, I attach [here](https://github.com/user-attachments/files/16411048/Archiv.zip) the zip file with the relevant files to be copied in the Obsidian folder.

I still need to fix compatibility with Windows. Certain features do not work there as expected yet, because Windows assumes `\` and MacOS/Linux uses `/` in the path.

Before releasing the new version, I want to have it tested properly, fix all Windows issues, and document the changes and new features.

**Comment by alberti42** [comment]
I have released the new version, which also fixes the problems with Windows. You can update the plugin. The clipboard now works.

**Comment by QNoir** [comment]
thanks! 
I have checked on both platforms - Win and Mac - everything works as it should!
