### ISSUE TITLE
Delete link and file deletes only the file

### ISSUE THREAD

**Issue by tprotopopescu** [alberti42/obsidian-import-attachments-plus#5]
When I right click on a link and select 'delete link and file' only the file is deleted. This is with the option to delete wikilinks enabled from settings. 

I only just started using the plugin so I can't say if this is unique to the latest version. 

Great plugin, very helpful!

**Comment by alberti42** [comment]
I have a created a new release, 1.5.7. It does not change the logic. So I don't expect it will resolve your problem. However, it gives detailed information on the console about what could possibly go wrong. Before there was just a generic message, while now I have a message for each check-point where something could go wrong. So, if you can tell me what you see on the development console, I may be able to better figure out what the problem is.

PS: If you are not familiar about how to open the developer console, check these instructions https://forum.obsidian.md/t/opening-developer-console/66755

**Comment by tprotopopescu** [comment]
My apologies for taking so long to get back to you, things got busy at work for a while. And thank you for looking in to this so quickly. 

After updating to the latest version it works as expected now. I guess it might have just been some kink in my system (I did try it repeatedly, it was not just a one off)? I'm sorry to have taken up your time with it.

**Comment by alberti42** [comment]
Thanks for your feedback!
