### ISSUE TITLE
Canvas paste image error

### ISSUE THREAD

**Issue by Prynka1995** [alberti42/obsidian-import-attachments-plus#6]
Hi, 
When plugin is turned on, then I cant paste an image from buffer into canvas.
But when plugin is turned off, then an image form buffer could be pasted.

What should I do?

**Comment by alberti42** [comment]
I will look into it in the next days. I did not test canvas since I don't use them myself. Once fixed, I will write back to you.

**Comment by alberti42** [comment]
I have implemented a fix that allows you for the moment to work with canvas and the plugin for importing files. More support will be implemented in the future, but you should already be able to resume your workflow.

I close this issue because a similar one was recently opened under this [link](https://github.com/alberti42/obsidian-import-attachments-plus/issues/8). You are welcome to post there your comments.
